# Generated by Django 2.0.3 on 2018-03-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='type',
            new_name='Type',
        ),
    ]
