# Generated by Django 2.0.3 on 2018-03-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20180325_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='total_score',
            field=models.FloatField(default=0),
        ),
    ]
