# Generated by Django 2.0.4 on 2018-05-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20180325_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='average',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='total_score',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='voted',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Type',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
