# Generated by Django 2.0.4 on 2018-05-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20180516_1057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='User',
        ),
    ]
